[workspace]
resolver = "2"

members = [
    "genesis",
    "crates/uat-core",
    "crates/uat-crypto", 
    "crates/uat-network", 
    "crates/uat-node",
    "crates/uat-consensus",
    # "crates/uat-vm",
    # "crates/uat-p2p",
]
