[workspace]
resolver = "2"

members = ["crates/uat-core",
    "genesis",
    # Modul lain akan kita aktifkan nanti saat kita membuatnya:
    # "crates/uat-core",
    # "crates/uat-consensus",
    # "crates/uat-vm",
    # "crates/uat-p2p",
    # "crates/uat-crypto",
]
