name: flutter_wallet
description: "Unauthority (UAT) Wallet - Secure blockchain wallet with Tor privacy"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
  crypto: ^3.0.3
  bip39: ^1.0.6
  provider: ^6.1.1
  socks5_proxy: ^2.1.1
  path_provider: ^2.1.2
  path: ^1.9.0
  uuid: ^4.3.3
  flutter_rust_bridge: ^2.11.1
  ffi: ^2.1.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
